// Shoe catalog. This is the only place shoe specs live — scoring and
// "why this fits you" copy are derived from these fields at runtime,
// never hardcoded per shoe.

import type { Shoe } from './types';

export const CATALOG: Shoe[] = [
  { id: 'nk-maxfly', brand: 'Nike', model: 'Air Zoom Maxfly 2', role: 'Sprint Spike', price: 200, weight: 132, pins: 9, plate: 'Carbon Air Zoom', plateRigidity: 'rigid', drop: 3, cushion: 'Moderate', forefootCushion: 'Moderate', heelCushion: 'Minimal', events: ['sprints'], surfaces: ['mondo', 'rubber'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#20488F', acc: '#D6462C', img: '/assets/ref2.png', pitch: 'An Air Zoom pod and full carbon plate built to hold top-end speed down the straight.' },
  { id: 'ad-primesp', brand: 'adidas', model: 'Adizero Prime SP2', role: 'Sprint Spike', price: 200, weight: 132, pins: 8, plate: 'Carbon EnergyRods', plateRigidity: 'rigid', drop: 3, cushion: 'Minimal', forefootCushion: 'Minimal', heelCushion: 'Minimal', events: ['sprints'], surfaces: ['mondo', 'rubber'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#16336B', acc: '#20488F', img: '/assets/spike-red.png', pitch: 'Stiff EnergyRods and a locked-down upper for pure block-to-tape sprinting.' },
  { id: 'nk-jafly', brand: 'Nike', model: 'Ja Fly 4', role: 'Sprint / Hurdle', price: 70, weight: 118, pins: 8, plate: 'Pebax', plateRigidity: 'rigid', drop: 2, cushion: 'Minimal', forefootCushion: 'Minimal', heelCushion: 'Minimal', events: ['sprints', 'hurdles'], surfaces: ['mondo', 'rubber'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#141109', acc: '#D6462C', img: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?fm=jpg&q=70&w=640&h=460&fit=crop&auto=format', pitch: 'A featherweight, affordable sprint spike that punches well above its price.' },
  { id: 'pu-tokyo', brand: 'Puma', model: 'evoSPEED Tokyo Sprint', role: 'Sprint Spike', price: 170, weight: 130, pins: 8, plate: 'Carbon', plateRigidity: 'rigid', drop: 3, cushion: 'Minimal', forefootCushion: 'Minimal', heelCushion: 'Minimal', events: ['sprints'], surfaces: ['mondo', 'rubber'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#2E6E63', acc: '#C9962B', img: '/assets/ref1.png', pitch: 'A springy carbon plate tuned for aggressive forefoot sprinters.' },
  { id: 'nk-rival', brand: 'Nike', model: 'Zoom Rival Multi', role: 'Multi-Event', price: 70, weight: 190, pins: 8, plate: 'Pebax', plateRigidity: 'rigid', drop: 5, cushion: 'Firm', forefootCushion: 'Moderate', heelCushion: 'Moderate', events: ['sprints', 'hurdles', 'jumpsHorizontal'], surfaces: ['mondo', 'rubber'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#141109', acc: '#2E6E63', img: '/assets/spike-nike-rival.png', pitch: 'One do-it-all spike for sprints, hurdles and the horizontal jumps — the team-kit workhorse.' },
  { id: 'ad-ambition', brand: 'adidas', model: 'Adizero Ambition', role: 'Hurdle / 400m', price: 110, weight: 165, pins: 6, plate: 'Glass-fibre', plateRigidity: 'rigid', drop: 5, cushion: 'Moderate', forefootCushion: 'Moderate', heelCushion: 'Moderate', events: ['hurdles', 'sprints', 'middle'], surfaces: ['mondo', 'rubber'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#20488F', acc: '#C9962B', img: '/assets/ref7.png', pitch: 'Enough plate for the long hurdles, enough give to survive the home straight of a 400.' },
  { id: 'nk-victory', brand: 'Nike', model: 'Zoom Victory 6', role: 'Middle-Distance', price: 150, weight: 96, pins: 6, plate: 'Pebax', plateRigidity: 'moderate', drop: 4, cushion: 'Minimal', forefootCushion: 'Minimal', heelCushion: 'Moderate', events: ['middle', 'distance'], surfaces: ['mondo', 'rubber'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#20488F', acc: '#C9962B', img: '/assets/spike-blue.png', pitch: 'A ZoomX-cushioned plate that stays light enough to kick off the final bend.' },
  { id: 'nb-mdx', brand: 'New Balance', model: 'FuelCell MD-X', role: 'Middle-Distance', price: 160, weight: 120, pins: 6, plate: 'Carbon FuelCell', plateRigidity: 'moderate', drop: 4, cushion: 'Moderate', forefootCushion: 'Moderate', heelCushion: 'Moderate', events: ['middle', 'distance'], surfaces: ['mondo', 'rubber'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#141109', acc: '#D6462C', img: 'https://images.unsplash.com/photo-1539185441755-769473a23570?fm=jpg&q=70&w=640&h=460&fit=crop&auto=format', pitch: 'FuelCell foam over a carbon plate for a rolling, resilient 800/1500 ride.' },
  { id: 'pu-dist', brand: 'Puma', model: 'evoSPEED Distance', role: 'Middle-Distance', price: 120, weight: 140, pins: 6, plate: 'Carbon', plateRigidity: 'moderate', drop: 5, cushion: 'Moderate', forefootCushion: 'Moderate', heelCushion: 'Moderate', events: ['middle', 'distance'], surfaces: ['mondo'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#3C5A3A', acc: '#C9962B', img: 'https://images.unsplash.com/photo-1562183241-b937e95585b6?fm=jpg&q=70&w=640&h=460&fit=crop&auto=format', pitch: 'A forgiving plate and cushioned heel for athletes doubling across distances.' },
  { id: 'nk-dragonfly', brand: 'Nike', model: 'Dragonfly 2', role: 'Distance Spike', price: 150, weight: 130, pins: 6, plate: 'Pebax + ZoomX', plateRigidity: 'moderate', drop: 5, cushion: 'Moderate', forefootCushion: 'Moderate', heelCushion: 'Moderate', events: ['distance', 'middle'], surfaces: ['mondo'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#2E6E63', acc: '#EFE6D2', img: '/assets/ref9.png', pitch: 'ZoomX under a translucent plate — the go-to for the 5000m and 10,000m.' },
  { id: 'ad-avanti', brand: 'adidas', model: 'Adizero Avanti TYO', role: 'Distance Spike', price: 140, weight: 135, pins: 6, plate: 'EnergyRods', plateRigidity: 'moderate', drop: 5, cushion: 'Moderate', forefootCushion: 'Moderate', heelCushion: 'Moderate', events: ['distance', 'middle'], surfaces: ['mondo'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#C1402A', acc: '#20488F', img: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?fm=jpg&q=70&w=640&h=460&fit=crop&auto=format', pitch: 'Lightstrike foam and rods that keep the legs fresh deep into the longer races.' },
  { id: 'nb-ldx', brand: 'New Balance', model: 'SuperComp LD-X', role: 'Distance Spike', price: 150, weight: 128, pins: 6, plate: 'Carbon', plateRigidity: 'moderate', drop: 6, cushion: 'Moderate', forefootCushion: 'Moderate', heelCushion: 'Max', events: ['distance', 'middle'], surfaces: ['mondo'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#16336B', acc: '#D6462C', img: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?fm=jpg&q=70&w=640&h=460&fit=crop&auto=format', pitch: 'A tall, legal foam stack over carbon for a plush long-distance spike ride.' },
  { id: 'nk-hj', brand: 'Nike', model: 'High Jump Elite', role: 'Jumps Spike', price: 130, weight: 240, pins: 11, plate: 'Rigid full', plateRigidity: 'rigid', drop: 8, cushion: 'Firm', forefootCushion: 'Moderate', heelCushion: 'Firm', events: ['jumpsHigh'], surfaces: ['mondo', 'rubber'], isThrowShoe: false, hasHeelPins: true, xcGrip: false, upperProtection: 'standard', body: '#6D3A5D', acc: '#C9962B', img: 'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?fm=jpg&q=70&w=640&h=460&fit=crop&auto=format', pitch: 'A rigid heel plate and dense pin array to plant and convert speed into height.' },
  { id: 'nk-tj', brand: 'Nike', model: 'Triple Jump Elite 2', role: 'Jumps Spike', price: 130, weight: 250, pins: 11, plate: 'Rigid full', plateRigidity: 'rigid', drop: 7, cushion: 'Firm', forefootCushion: 'Moderate', heelCushion: 'Firm', events: ['jumpsHorizontal'], surfaces: ['mondo', 'rubber'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#141109', acc: '#D6462C', img: 'https://images.unsplash.com/photo-1543508282-6319a3e2621f?fm=jpg&q=70&w=640&h=460&fit=crop&auto=format', pitch: 'Built to survive the hop-step-jump pounding with a locked, protective ride.' },
  { id: 'ad-jumpstar', brand: 'adidas', model: 'Jumpstar', role: 'Jumps Spike', price: 80, weight: 260, pins: 11, plate: 'TPU plate', plateRigidity: 'rigid', drop: 8, cushion: 'Firm', forefootCushion: 'Moderate', heelCushion: 'Firm', events: ['jumpsHorizontal', 'jumpsHigh'], surfaces: ['mondo', 'rubber'], isThrowShoe: false, hasHeelPins: true, xcGrip: false, upperProtection: 'standard', body: '#20488F', acc: '#C9962B', img: 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?fm=jpg&q=70&w=640&h=460&fit=crop&auto=format', pitch: 'A versatile, budget jumps spike that spans long, triple and high jump.' },
  { id: 'nk-rot', brand: 'Nike', model: 'Zoom Rotational 6', role: 'Throws Shoe', price: 110, weight: 300, pins: 0, plate: 'Flat pivot', plateRigidity: 'none', drop: 0, cushion: 'Minimal', forefootCushion: 'Minimal', heelCushion: 'Minimal', events: ['throws'], surfaces: ['mondo', 'rubber'], isThrowShoe: true, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#141109', acc: '#D6462C', img: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?fm=jpg&q=70&w=640&h=460&fit=crop&auto=format', pitch: 'A smooth, low-friction pivot sole for the discus and shot circle.' },
  { id: 'ad-shotput', brand: 'adidas', model: 'Adizero Shotput', role: 'Throws Shoe', price: 90, weight: 330, pins: 0, plate: 'Flat pivot', plateRigidity: 'none', drop: 0, cushion: 'Firm', forefootCushion: 'Firm', heelCushion: 'Firm', events: ['throws'], surfaces: ['mondo', 'rubber'], isThrowShoe: true, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#16336B', acc: '#C9962B', img: 'https://images.unsplash.com/photo-1605348532760-6753d2c43329?fm=jpg&q=70&w=640&h=460&fit=crop&auto=format', pitch: 'A stable, flat platform and locked heel for glide and rotational putters.' },
  { id: 'nk-vapor', brand: 'Nike', model: 'Vaporfly 3', role: 'Road Racer', price: 260, weight: 196, pins: 0, plate: 'Full carbon', plateRigidity: 'flexible', drop: 8, cushion: 'Max', forefootCushion: 'Max', heelCushion: 'Max', events: ['road'], surfaces: ['road'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#16336B', acc: '#D6462C', img: '/assets/ref8.png', pitch: 'ZoomX foam and a full carbon plate — the benchmark 5k-to-marathon super-shoe.' },
  { id: 'ad-adiospro', brand: 'adidas', model: 'Adizero Adios Pro 3', role: 'Road Racer', price: 250, weight: 215, pins: 0, plate: 'EnergyRods 2.0', plateRigidity: 'flexible', drop: 6, cushion: 'Max', forefootCushion: 'Max', heelCushion: 'Max', events: ['road'], surfaces: ['road'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#20488F', acc: '#D6462C', img: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?fm=jpg&q=70&w=640&h=460&fit=crop&auto=format', pitch: 'Lightstrike Pro and carbon rods that mimic the bones of the foot for the marathon.' },
  { id: 'as-metaspeed', brand: 'ASICS', model: 'Metaspeed Sky Paris', role: 'Road Racer', price: 250, weight: 180, pins: 0, plate: 'Full carbon', plateRigidity: 'flexible', drop: 5, cushion: 'Max', forefootCushion: 'Max', heelCushion: 'Max', events: ['road'], surfaces: ['road'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#2E6E63', acc: '#20488F', img: '/assets/ref4.png', pitch: 'FF Turbo foam tuned for stride-length runners who want to fly the flats.' },
  { id: 'sa-endorphin', brand: 'Saucony', model: 'Endorphin Pro 4', role: 'Road Racer', price: 225, weight: 210, pins: 0, plate: 'Full carbon', plateRigidity: 'flexible', drop: 8, cushion: 'Max', forefootCushion: 'Max', heelCushion: 'Max', events: ['road'], surfaces: ['road'], isThrowShoe: false, hasHeelPins: false, xcGrip: false, upperProtection: 'standard', body: '#6D3A5D', acc: '#C9962B', img: '/assets/ref5.png', pitch: 'PWRRUN PB and a SpeedRoll geometry that tips you forward mile after mile.' },
  { id: 'nk-xc', brand: 'Nike', model: 'Zoom Rival XC 6', role: 'Cross-Country', price: 65, weight: 200, pins: 6, plate: 'Pebax', plateRigidity: 'flexible', drop: 6, cushion: 'Moderate', forefootCushion: 'Moderate', heelCushion: 'Moderate', events: ['xc', 'distance'], surfaces: ['terrain'], isThrowShoe: false, hasHeelPins: false, xcGrip: true, upperProtection: 'reinforced', body: '#3C5A3A', acc: '#C9962B', img: '/assets/ref6.png', pitch: 'Removable pins and an aggressive outsole that bite into mud and grass.' },
  { id: 'ad-xc', brand: 'adidas', model: 'XCS Trail', role: 'Cross-Country', price: 80, weight: 210, pins: 6, plate: 'TPU', plateRigidity: 'flexible', drop: 6, cushion: 'Moderate', forefootCushion: 'Moderate', heelCushion: 'Moderate', events: ['xc', 'distance'], surfaces: ['terrain'], isThrowShoe: false, hasHeelPins: false, xcGrip: true, upperProtection: 'reinforced', body: '#141109', acc: '#20488F', img: '/assets/adidas-xcs.png', pitch: 'A wrapped, water-shedding upper and lugged grip for the worst XC conditions.' },
];
